@startuml
'https://plantuml.com/sequence-diagram


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title 入室のシーケンス図
クライアントA -> サーバー:入室、ユーザー情報
rnote over サーバー:最初に入った人(クライアントA)を\nマスタークライアントにする
クライアントA <-- サーバー:現在参加しているユーザー情報
rnote over クライアントA:プレイヤーを生成する

クライアントB -> サーバー:入室、ユーザー情報
クライアントB <-- サーバー:参加しているユーザー情報
クライアントA <-- サーバー:クライアントBのユーザー情報
rnote over クライアントA,クライアントB:プレイヤーを生成する

クライアントC -> サーバー:入室、ユーザー情報
クライアントC <-- サーバー:参加しているユーザー情報
クライアントA <-- サーバー:クライアントCのユーザー情報
クライアントB <-- サーバー:クライアントCのユーザー情報
rnote over クライアントA,クライアントC:プレイヤーを生成する
@enduml