@startuml
'https://plantuml.com/sequence-diagram


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title キャラクター情報更新のシーケンス図
rnote over クライアントA,クライアントC:マスタークライアントの場合は13_マスタークライアントの更新シーケンス図を参照
rnote over クライアントA,クライアントC:コルーチンで定期的に更新リクエストをサーバーに送信する
クライアントA -> サーバー:(座標,回転,アニメーションID,アクティブ状態)をサーバーに送信
クライアントB <-- サーバー:クライアントAの更新通知を受信
クライアントC <-- サーバー:クライアントAの更新通知を受信
rnote over クライアントB,クライアントC:クライアントAの情報を更新する

クライアントB -> サーバー:(座標,回転,アニメーションID,アクティブ状態)をサーバーに送信
クライアントA <-- サーバー:クライアントBの更新通知を受信
クライアントC <-- サーバー:クライアントBの更新通知を受信
rnote over クライアントA:クライアントBの情報を更新する
rnote over クライアントC:クライアントBの情報を更新する

クライアントC -> サーバー:(座標,回転,アニメーションID,アクティブ状態)をサーバーに送信
クライアントA <-- サーバー:クライアントCの更新通知を受信
クライアントB <-- サーバー:クライアントCの更新通知を受信
rnote over クライアントA,クライアントB:クライアントCの情報を更新する
@enduml