@startuml
'https://plantuml.com/sequence-diagram


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title 移動のシーケンス図
rnote over クライアントA:自分の移動処理
クライアントA -> サーバー:座標情報をサーバーに送信
クライアントB <-- サーバー:クライアントAが移動した通知を受信
クライアントC <-- サーバー:クライアントAが移動した通知を受信
rnote over クライアントB,クライアントC:クライアントAを受信した座標に移動

rnote over クライアントB:自分の移動処理
クライアントB -> サーバー:座標情報をサーバーに送信
クライアントA <-- サーバー:クライアントBが移動した通知を受信
クライアントC <-- サーバー:クライアントBが移動した通知を受信
rnote over クライアントA:クライアントBを受信した座標に移動
rnote over クライアントC:クライアントBを受信した座標に移動

rnote over クライアントC:自分の移動処理
クライアントC -> サーバー:座標情報をサーバーに送信
クライアントA <-- サーバー:クライアントCが移動した通知を受信
クライアントB <-- サーバー:クライアントCが移動した通知を受信
rnote over クライアントA,クライアントB:クライアントCを受信した座標に移動
@enduml