@startuml
'https://plantuml.com/sequence-diagram

'[メモ]'
'ルーム内 => 該当のUIを削除、クライアントサイドのデータ削除'
'ゲーム準備中 => キャラクターの生成が終了してからキャラクターとクライアントサイドのデータ削除'
'ゲーム中 => キャラクター削除、クライアントサイドのデータ削除'
'リザルトなど他のシーン => クライアントサイドのデータ削除'


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title 切断時のシーケンス図
rnote over クライアントA:切断
rnote over サーバー:クライアントAの切断を検知、\nクライアントAの情報を削除
/'クライアントB <-- サーバー:クライアントAが退室した通知
クライアントC <-- サーバー:クライアントAが退室した通知'/

/'alt ゲームの進行状態:ルーム待機中 && ルームのホストがクライアントAの場合
クライアントB -> サーバー:退室処理のリクエスト
クライアントC -> サーバー:退室処理のリクエスト
end

alt ゲームの進行状態:ルーム待機中 && ルームのホストがクライアントAの場合
クライアントB -> サーバー:退室処理のリクエスト
クライアントC -> サーバー:退室処理のリクエスト
end'/

クライアントB <-- サーバー:クライアントAの退室処理
クライアントC <-- サーバー:クライアントAの退室処理

alt クライアントA(入室順番が１)がマスタークライアントだった場合
rnote over サーバー:クライアントB(入室順番が２)を\nマスタークライアントにする
クライアントB <-- サーバー:マスタークライアント任命通知(現在のゲームの残り時間も送信)
rnote over クライアントB:制限時間のカウントダウン開始
end

alt ゲームの進行状態:ゲームの準備中(ロード画面) && 全員が準備完了している
クライアントB <-- サーバー:ゲーム開始のカウントダウン開始通知
クライアントC <-- サーバー:ゲーム開始のカウントダウン開始通知
end

alt ゲームの進行状態:ゲーム開始のカウントダウン中 && 全員が準備完了している
クライアントB <-- サーバー:ゲーム開始通知
クライアントC <-- サーバー:ゲーム開始通知
end

@enduml クライアントA