@startuml
'https://plantuml.com/sequence-diagram

'[メモ]'
'ルーム内 => 該当のUIを削除、クライアントサイドのデータ削除'
'ゲーム準備中 => キャラクターの生成が終了してからキャラクターとクライアントサイドのデータ削除'
'ゲーム中 => キャラクター削除、クライアントサイドのデータ削除'
'リザルトなど他のシーン => クライアントサイドのデータ削除'


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title 切断時のシーケンス図
rnote over クライアントA:切断
rnote over サーバー:クライアントAの切断を検知、\nクライアントAの情報を削除

alt 他に参加しているユーザーが一人でも何かしらの準備完了をしていた場合
rnote over サーバー:クライアントAの準備完了処理
クライアントB <-- サーバー:クライアントAの準備完了通知
クライアントC <-- サーバー:クライアントAの準備完了通知
end

クライアントB <-- サーバー:クライアントAの退室処理
クライアントC <-- サーバー:クライアントAの退室処理

@enduml クライアントA