@startuml
'https://plantuml.com/sequence-diagram

'[メモ]'
'ルーム内 => 該当のUIを削除、クライアントサイドのデータ削除'
'ゲーム準備中 => キャラクターの生成が終了してからキャラクターとクライアントサイドのデータ削除'
'ゲーム中 => キャラクター削除、クライアントサイドのデータ削除'
'リザルトなど他のシーン => クライアントサイドのデータ削除'


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title ゲーム開始までのシーケンス図

クライアントA -> サーバー:ゲーム開始準備完了
rnote over サーバー:全員準備完了したかチェック
クライアントB -> サーバー:ゲーム開始準備完了
rnote over サーバー:全員準備完了したかチェック
クライアントC -> サーバー:ゲーム開始準備完了
rnote over サーバー:全員準備完了したかチェック
クライアントA <-- サーバー:ゲーム開始のカウントダウン開始通知
クライアントB <-- サーバー:ゲーム開始のカウントダウン開始通知
クライアントC <-- サーバー:ゲーム開始のカウントダウン開始通知

rnote over クライアントA,クライアントC:各自でカウントダウン実行
クライアントA -> サーバー:カウントダウン終了通知
rnote over サーバー:全員カウントダウンが終了したかチェック
クライアントB -> サーバー:カウントダウン終了通知
rnote over サーバー:全員カウントダウンが終了したかチェック
クライアントC -> サーバー:カウントダウン終了通知
rnote over サーバー:全員カウントダウンが終了したかチェック
クライアントA <-- サーバー:ゲーム開始通知
クライアントB <-- サーバー:ゲーム開始通知
クライアントC <-- サーバー:ゲーム開始通知
rnote over クライアントA,クライアントC:ゲーム開始
@enduml クライアントA