@startuml
'https://plantuml.com/sequence-diagram

participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title ゲーム開始までのシーケンス図

rnote over クライアントA,クライアントC:現在のシーン：RoomScene
クライアントA -> サーバー:ゲーム開始準備完了
rnote over サーバー:全員準備完了したかチェック
クライアントB -> サーバー:ゲーム開始準備完了
rnote over サーバー:全員準備完了したかチェック
クライアントC -> サーバー:ゲーム開始準備完了
rnote over サーバー:全員準備完了したかチェック
クライアントA <-- サーバー:シーン遷移＆ゲーム開始のカウントダウン開始通知
クライアントB <-- サーバー:シーン遷移＆ゲーム開始のカウントダウン開始通知
クライアントC <-- サーバー:シーン遷移＆ゲーム開始のカウントダウン開始通知

rnote over クライアントA,クライアントC:現在のシーン：GameScene
rnote over クライアントA,クライアントC:各自でカウントダウン実行
クライアントA -> サーバー:カウントダウン終了通知
rnote over サーバー:全員カウントダウンが終了したかチェック
クライアントB -> サーバー:カウントダウン終了通知
rnote over サーバー:全員カウントダウンが終了したかチェック
クライアントC -> サーバー:カウントダウン終了通知
rnote over サーバー:全員カウントダウンが終了したかチェック
クライアントA <-- サーバー:ゲーム開始通知
クライアントB <-- サーバー:ゲーム開始通知
クライアントC <-- サーバー:ゲーム開始通知
rnote over クライアントA,クライアントC:ゲーム開始
@enduml クライアントA