@startuml
'https://plantuml.com/sequence-diagram


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title アイテム取得のシーケンス図
rnote over クライアントA:アイテムに触れた
クライアントA -> サーバー:クライアントAが触れたアイテムの名前
rnote over サーバー:クライアントAが入手しようとしているアイテム名を\n他のクライアントが使用しているかチェック
alt チェックに問題がなかった場合
クライアントA <-- サーバー:クライアントAの接続ID,アイテム名,オプションの値(効果値など)
クライアントB <-- サーバー:クライアントAの接続ID,アイテム名,オプションの値(効果値など)
クライアントC <-- サーバー:クライアントAの接続ID,アイテム名,オプションの値(効果値など)
alt アイテムのタイプがコイン(ポイント)の場合
rnote over クライアントA,クライアントC:オプションの値をクライアントAの所持ポイント(UI)に反映
rnote over クライアントA,クライアントC:同じアイテム名を探して削除する
end
alt アイテムのタイプがコイン(ポイント)ではない場合
rnote over クライアントA:アイテムの効果を反映させる
rnote over クライアントA,クライアントC:アイテムを使用するアニメーションや\nパーティクルがあればクライアントAに反映させる
rnote over クライアントA,クライアントC:同じアイテム名を探して削除する
end
end
rnote over サーバー:現在のゲームが終了したらアイテムの使用履歴を初期化
@enduml