@startuml
'https://plantuml.com/sequence-diagram


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title 動的なオブジェクトのシーケンス図
rnote over クライアントA:マスタークライアントにする
クライアントA -> サーバー:生成するオブジェクトのID、移動方向、生成する場所
rnote over サーバー:オブジェクトの名前を生成
クライアントA <-- サーバー:生成するオブジェクトのID、移動方向、生成する場所、名前
クライアントB <-- サーバー:生成するオブジェクトのID、移動方向、生成する場所、名前
クライアントC <-- サーバー:生成するオブジェクトのID、移動方向、生成する場所、名前
rnote over クライアントA,クライアントC:オブジェクトを生成する
@enduml