@startuml
'https://plantuml.com/sequence-diagram


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber
title 13_マスタークライアントの更新シーケンス図
rnote over クライアントA:マスタークライアントにする
クライアントA -> サーバー:(アクティブになっている動的なオブジェクト(初めから常に存在し動き回っているモノ)の情報\n[オブジェクトのタイプID,ユニークな名前,座標、回転...(オブジェクトのタイプごとで異なる)],\nキャラクター(クライアントA)の情報[03_シーケンス図参照])を送信
クライアントB <-- サーバー:マスタークライアントの更新情報を受信
クライアントC <-- サーバー:マスタークライアントの更新情報を受信
rnote over クライアントB,クライアントC:マスタークライアントの情報を更新する
@enduml